spring:
  rabbitmq:
    username: ENC(Ore1c39ToJzASdjY4A8LGw==) # 明文guest
    password: ENC(Ore1c39ToJzASdjY4A8LGw==) #明文guest
    host: localhost #服务器ip
    virtual-host: / #虚拟空间地址
    port: 5672  #rabbit服务器默认端口
    publisher-confirms: true #配置发布消息确认回调
jasypt:
  encryptor:
    password: cross