spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
  rabbitmq:
    username: ENC(Ore1c39ToJzASdjY4A8LGw==) #用户名( 明文guest)
    password: ENC(Ore1c39ToJzASdjY4A8LGw==) #密码(明文guest)
    host: localhost #服务器ip
    virtual-host: / #虚拟空间地址
    port: 5672  #rabbit服务器默认端口
    publisher-confirms: true #配置发布消息确认回调
server:
  port: 8881
  compression:
    enabled: true #是否启用gzip压缩
    mime-types: application/json,application/xml,text/html,text/xml,text/plain #需要压缩的内容格式
    min-response-size: 2048 #响应内容大于{min-response-size}字节时，才会压缩，默认：2048字节
swagger:
  enable: true
jasypt:
  encryptor:
    password: cross
